site_name: carla_2d_deeprl
site_description: 基于 CARLA 的极简 2D 深度强化学习环境
site_url: https://mt960.github.io/nn/src/carla_2d_deeprl/
repo_url: https://github.com/mt960/nn/tree/main/src/carla_2d_deeprl

nav:
  - 首页: index.md

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  - extra
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
